{% set name = "django-simple-history" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_simple_history-{{ version }}.tar.gz
  sha256: e70d70fb4cc2af60a50904f1420d5a6440d24efddceba3daeff8b02d269ebdf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - simple_history
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/treyhunner/django-simple-history
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Store model history and view/revert changes from admin site.'
  description: django-simple-history stores Django model state on every create/update/delete.
  doc_url: https://django-simple-history.readthedocs.io/
  dev_url: https://github.com/treyhunner/django-simple-history

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
