{% set name = "django-simple-history" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_simple_history-{{ version }}.tar.gz
  sha256: ac3b7ca8b0d33f7ea6be8fe7fc98cf43415efa500ff5dfe736fbd1ebc0cf39f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8
    - django >=4.2

test:
  imports:
    - simple_history
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/treyhunner/django-simple-history
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Store model history and view/revert changes from admin site.'
  description: django-simple-history stores Django model state on every create/update/delete.
  doc_url: https://django-simple-history.readthedocs.io/
  dev_url: https://github.com/treyhunner/django-simple-history

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
