{% set name = "django-simple-history" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-simple-history-{{ version }}.tar.gz
  sha256: eef2943d7c846270f11c8136f38a3ba00de2bebd7b1b89037de5d9b148ed677a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - asgiref >=3.6
    - django >=3.2

test:
  imports:
    - simple_history
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/treyhunner/django-simple-history
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Store model history and view/revert changes from admin site.'
  description: django-simple-history stores Django model state on every create/update/delete.
  doc_url: https://django-simple-history.readthedocs.io/
  dev_url: https://github.com/treyhunner/django-simple-history

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
